export interface Topic {
  sno: number;
  system: string;
  title: string;
  duration: string;
}

export const topics: Topic[] = [
  {sno: 1, system: "General", title: "5 Hacks to Complete Internal Medicine for NEET PG", duration: "44:39"},
  {sno: 2, system: "Cardiology", title: "Heart Sounds Part 1", duration: "1:47:39"},
  {sno: 3, system: "", title: "Heart Sounds Part 2", duration: "40:37"},
  {sno: 4, system: "", title: "Heart Sounds Part 3", duration: "1:28:33"},
  {sno: 5, system: "", title: "Mitral Valve Prolapse", duration: "35:53"},
  {sno: 6, system: "", title: "Mitral Regurgitation", duration: "48:08"},
  {sno: 7, system: "", title: "Aortic Stenosis", duration: "51:27"},
  {sno: 8, system: "", title: "Aortic Regurgitation", duration: "48:33"},
  {sno: 9, system: "", title: "Tricuspid Stenosis", duration: "19:43"},
  {sno: 10, system: "", title: "Tricuspid Regurgitation, Pulmonic Stenosis and Pulmonic Regurgitation", duration: "50:08"},
  {sno: 11, system: "", title: "Murmurs", duration: "1:49:43"},
  {sno: 12, system: "", title: "Takotsubo Cardiomyopathy and Brugada Syndrome", duration: "42:37"},
  {sno: 13, system: "", title: "ECG and Arrhythmias", duration: "2:51:56"},
  {sno: 14, system: "", title: "ECG Changes in Hypokalemia & Hyperkalemia", duration: "33:04"},
  {sno: 15, system: "", title: "Ischemic Heart Disease Part 1", duration: "1:51:21"},
  {sno: 16, system: "", title: "Ischemic Heart Disease Part 2", duration: "1:54:14"},
  {sno: 17, system: "", title: "Symptomatic Bradycardia with a Pulse", duration: "44:28"},
  {sno: 18, system: "", title: "Congenital Heart Disease", duration: "1:39:26"},
  {sno: 19, system: "", title: "Metabolic Syndrome X and Syndrome Z", duration: "25:21"},
  {sno: 20, system: "", title: "Hypertension", duration: "1:41:09"},
  {sno: 21, system: "", title: "Diseases of Pericardium", duration: "1:19:35"},
  {sno: 22, system: "", title: "Congestive Heart Failure", duration: "1:30:30"},
  {sno: 23, system: "", title: "Bundle Branch Block", duration: "22:20"},
  {sno: 24, system: "", title: "Rheumatic Heart Disease", duration: "1:08:34"},
  {sno: 25, system: "", title: "Infective Endocarditis", duration: "1:15:21"},
  {sno: 26, system: "", title: "Cardiomyopathy", duration: "1:35:48"},
  {sno: 27, system: "", title: "Multifocal Atrial Tachycardia", duration: "13:50"},
  {sno: 28, system: "", title: "Cardiology Image Based Question", duration: "1:11:54"},
  {sno: 29, system: "Emergency", title: "Basic Life Support", duration: "30:05"},
  {sno: 30, system: "", title: "Pulseless Electrical Activity", duration: "20:06"},
  {sno: 31, system: "", title: "Advanced Cardiac Life Support", duration: "45:14"},
  {sno: 32, system: "", title: "Mechanical Ventilation", duration: "35:26"},
  {sno: 33, system: "", title: "Massive Transfusion Protocol", duration: "21:56"},
  {sno: 34, system: "", title: "ARDS", duration: "47:14"},
  {sno: 35, system: "", title: "Snake Bite", duration: "33:14"},
  {sno: 36, system: "", title: "High Altitude Pulmonary Edema and Hypothermia", duration: "39:07"},
  {sno: 37, system: "Endocrinology", title: "Diabetes Mellitus Part 1", duration: "1:27:03"},
  {sno: 38, system: "", title: "Diabetes Mellitus Part 2", duration: "2:00:33"},
  {sno: 39, system: "", title: "Diabetic Ketoacidosis and Hyperosmolar Coma", duration: "1:12:06"},
  {sno: 40, system: "", title: "Diseases of Adrenal Gland", duration: "2:04:08"},
  {sno: 41, system: "", title: "Cushing Syndrome", duration: "49:43"},
  {sno: 42, system: "", title: "Diseases of Thyroid", duration: "1:59:30"},
  {sno: 43, system: "", title: "Pancreatic Neuroendocrine Tumors", duration: "51:21"},
  {sno: 44, system: "", title: "Disorders of Parathyroid Gland", duration: "1:28:46"},
  {sno: 45, system: "", title: "Multiple Endocrine Neoplasia", duration: "29:37"},
  {sno: 46, system: "", title: "Diseases of Anterior Pituitary", duration: "54:14"},
  {sno: 47, system: "", title: "Endocrinology Image Based Questions", duration: "10:14"},
  {sno: 48, system: "Nephrology", title: "Electrolyte imbalances", duration: "1:31:09"},
  {sno: 49, system: "", title: "Bartter Syndrome, Gitelman Syndrome, Liddle Syndrome and SIADH", duration: "59:31"},
  {sno: 50, system: "", title: "Ciliopathies", duration: "20:14"},
  {sno: 51, system: "", title: "Polycystic Kidney Disease", duration: "25:21"},
  {sno: 52, system: "", title: "Thrombotic Thrombocytopenic Purpura", duration: "19:22"},
  {sno: 53, system: "", title: "Kidney Urine analysis", duration: "42:07"},
  {sno: 54, system: "", title: "Acute Kidney Injury", duration: "1:27:14"},
  {sno: 55, system: "", title: "Chronic Kidney Disease", duration: "1:09:11"},
  {sno: 56, system: "", title: "Kidney Stone", duration: "30:14"},
  {sno: 57, system: "", title: "Renal Tubular Acidosis", duration: "27:01"},
  {sno: 58, system: "", title: "Nephrotic and Nephritic Syndrome Part 1", duration: "1:02:14"},
  {sno: 59, system: "", title: "Nephrotic and Nephritic Syndrome Part 2", duration: "1:33:31"},
  {sno: 60, system: "Gastrointestinal", title: "GI Bleeding", duration: "50:54"},
  {sno: 61, system: "", title: "Peptic Ulcer Disease", duration: "41:26"},
  {sno: 62, system: "", title: "Zollinger Ellison Syndrome", duration: "19:44"},
  {sno: 63, system: "", title: "Malabsorption Syndrome", duration: "1:02:37"},
  {sno: 64, system: "", title: "Inflammatory Bowel Disease", duration: "57:14"},
  {sno: 65, system: "", title: "Irritable Bowel Syndrome Part 1", duration: "17:41"},
  {sno: 66, system: "", title: "Irritable Bowel Syndrome Part 2", duration: "56:21"},
  {sno: 67, system: "Hematology", title: "Chronic Lymphocytic Leukemia", duration: "26:01"},
  {sno: 68, system: "", title: "Chronic Myeloid Leukemia", duration: "28:14"},
  {sno: 69, system: "", title: "Acute Myeloid Leukemia", duration: "31:31"},
  {sno: 70, system: "", title: "Acute Lymphoblastic Leukemia", duration: "35:21"},
  {sno: 71, system: "", title: "Multiple Myeloma", duration: "44:03"},
  {sno: 72, system: "", title: "Blood Components", duration: "19:21"},
  {sno: 73, system: "", title: "Complications of Blood Transfusion", duration: "1:02:01"},
  {sno: 74, system: "", title: "Hodgkin and Non-Hodgkin Lymphoma", duration: "48:37"},
  {sno: 75, system: "", title: "Thalassemia", duration: "59:21"},
  {sno: 76, system: "", title: "Sickle Cell Disease, G-6PD Deficiency and Hemolytic Anemias", duration: "43:57"},
  {sno: 77, system: "", title: "Sideroblastic Anemia", duration: "09:47"},
  {sno: 78, system: "", title: "Platelet Disorders", duration: "42:37"},
  {sno: 79, system: "Neurology", title: "Stroke", duration: "1:46:16"},
  {sno: 80, system: "", title: "Headache and Migraine", duration: "1:12:14"},
  {sno: 81, system: "", title: "Epilepsy and EEG", duration: "1:55:40"},
  {sno: 82, system: "", title: "Raised ICP and Brain Death", duration: "1:18:21"},
  {sno: 83, system: "", title: "Meningitis Part 1", duration: "36:26"},
  {sno: 84, system: "", title: "Meningitis Part 2", duration: "1:07:31"},
  {sno: 85, system: "", title: "Parkinsonism and Parkinson's Disease", duration: "1:18:43"},
  {sno: 86, system: "", title: "Myasthenia Gravis", duration: "49:07"},
  {sno: 87, system: "", title: "Guillain Barre Syndrome", duration: "42:16"},
  {sno: 88, system: "", title: "Alzheimer's Disease", duration: "43:16"},
  {sno: 89, system: "", title: "Multiple Sclerosis", duration: "1:06:11"},
  {sno: 90, system: "", title: "Neuromyelitis Optica Spectrum Disorder", duration: "21:26"},
  {sno: 91, system: "", title: "Amyotrophic Lateral Sclerosis and Motor Neuron Disease", duration: "39:11"},
  {sno: 92, system: "", title: "Syringomyelia and Conus Medullaris Syndrome", duration: "50:11"},
  {sno: 93, system: "", title: "Channelopathies", duration: "18:13"},
  {sno: 94, system: "", title: "Subarachnoid Hemorrhage", duration: "36:11"},
  {sno: 95, system: "", title: "Transient Ischemic Attack and Stroke Interventions", duration: "1:47:11"},
  {sno: 96, system: "", title: "Neurocysticercosis and Brain Tumors", duration: "56:01"},
  {sno: 97, system: "", title: "Intracranial Hemorrhage", duration: "54:11"},
  {sno: 98, system: "Rheumatology", title: "Systemic Lupus Erythematosus", duration: "1:07:11"},
  {sno: 99, system: "", title: "Rheumatoid Arthritis", duration: "32:16"},
  {sno: 100, system: "", title: "Crystal Arthropathy", duration: "26:26"},
  {sno: 101, system: "", title: "Vasculitis", duration: "47:16"},
  {sno: 102, system: "", title: "Scleroderma Sjogren Syndrome", duration: "37:51"},
  {sno: 103, system: "", title: "Sarcoidosis", duration: "45:21"},
  {sno: 104, system: "", title: "IgG4 Related Disease", duration: "07:31"},
  {sno: 105, system: "", title: "Axial Spondyloarthritis", duration: "25:21"},
  {sno: 106, system: "Hepatobiliary", title: "Hepatitis B", duration: "57:21"},
  {sno: 107, system: "", title: "Hepatitis C, D and Fulminant Hepatic Failure", duration: "1:01:04"},
  {sno: 108, system: "", title: "Hepatorenal Syndrome and Hepatopulmonary Syndrome", duration: "20:13"},
  {sno: 109, system: "", title: "Autoimmune Hepatitis", duration: "12:41"},
  {sno: 110, system: "", title: "Cirrhosis and its Complications", duration: "1:18:21"},
  {sno: 111, system: "", title: "PBC and PSC", duration: "14:31"},
  {sno: 112, system: "", title: "Wilson Disease and Hemochromatosis", duration: "47:11"},
  {sno: 113, system: "", title: "Alcoholic Hepatitis", duration: "27:11"},
  {sno: 114, system: "", title: "Hereditary Hyperbilirubinemias", duration: "25:11"},
  {sno: 115, system: "", title: "Paracetamol and Iron Toxicity", duration: "18:21"},
  {sno: 116, system: "", title: "Budd Chiari Syndrome", duration: "15:26"},
  {sno: 117, system: "Pulmonology", title: "Cystic Fibrosis", duration: "35:11"},
  {sno: 118, system: "", title: "Obstructive Sleep Apnea", duration: "30:26"},
  {sno: 119, system: "", title: "Pulmonary Thromboembolism", duration: "58:11"},
  {sno: 120, system: "", title: "Fat Embolism Syndrome", duration: "24:26"},
  {sno: 121, system: "", title: "Bronchiectasis", duration: "28:11"},
  {sno: 122, system: "", title: "Pneumonia", duration: "1:04:11"},
  {sno: 123, system: "", title: "Bronchial Asthma", duration: "1:25:21"},
  {sno: 124, system: "", title: "COPD", duration: "55:11"},
  {sno: 125, system: "", title: "Respiratory Failure", duration: "22:41"},
  {sno: 126, system: "", title: "Tuberculosis", duration: "54:41"},
  {sno: 127, system: "", title: "Interstitial Lung Disease", duration: "32:11"},
  {sno: 128, system: "", title: "Pulmonary Alveolar Proteinosis", duration: "10:11"},
  {sno: 129, system: "", title: "Pleural Effusion", duration: "55:21"},
  {sno: 130, system: "", title: "Pneumothorax", duration: "43:21"},
  {sno: 131, system: "", title: "Flow Volume Curve, Spirometry and DLCO", duration: "38:06"},
  {sno: 132, system: "", title: "ABG Analysis Simplified Part 1", duration: "1:06:58"},
  {sno: 133, system: "", title: "ABG Analysis Simplified Part 2", duration: "46:51"},
  {sno: 134, system: "", title: "ABG Analysis Simplified Part 3", duration: "31:15"},
  {sno: 135, system: "Infections", title: "Fever of Unknown Origin", duration: "40:23"},
  {sno: 136, system: "", title: "Dengue Fever", duration: "32:16"},
  {sno: 137, system: "", title: "Nipah, Zika and Monkeypox", duration: "21:03"},
  {sno: 138, system: "", title: "Pneumocystis Jirovecii", duration: "17:09"},
  {sno: 139, system: "", title: "Aspergillosis", duration: "21:01"},
  {sno: 140, system: "", title: "AIDS", duration: "59:04"},
  {sno: 141, system: "", title: "SARS COV-2-COVID-19", duration: "37:05"}
];
